/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kpu.fs.alpha;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Zac Laptop
 */
public class JFrame_Login extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_Login
     */
    public JFrame_Login() {
        
        //JFrame_Login.setSize(400, 400);
        //setSize(500, 500);   
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UserInput = new javax.swing.JTextField();
        PassInput = new javax.swing.JPasswordField();
        Title = new javax.swing.JLabel();
        User = new javax.swing.JLabel();
        Pass = new javax.swing.JLabel();
        Login = new javax.swing.JButton();
        Image_BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KPU-FS Login");
        setBackground(new java.awt.Color(204, 204, 204));
        setLocation(new java.awt.Point(500, 200));
        setMinimumSize(new java.awt.Dimension(500, 400));
        setName("LoginFrame"); // NOI18N
        setSize(new java.awt.Dimension(500, 380));
        getContentPane().setLayout(null);

        UserInput.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        UserInput.setText("user");
        getContentPane().add(UserInput);
        UserInput.setBounds(210, 140, 153, 19);

        PassInput.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        PassInput.setText("pass");
        getContentPane().add(PassInput);
        PassInput.setBounds(210, 180, 154, 19);

        Title.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setText("KPU Faculty Scheduler");
        getContentPane().add(Title);
        Title.setBounds(20, 20, 460, 100);

        User.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        User.setForeground(new java.awt.Color(255, 255, 255));
        User.setText("KPU ID:");
        getContentPane().add(User);
        User.setBounds(130, 140, 60, 17);

        Pass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Pass.setForeground(new java.awt.Color(255, 255, 255));
        Pass.setText("Password:");
        getContentPane().add(Pass);
        Pass.setBounds(130, 180, 70, 17);

        Login.setText("Login");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        getContentPane().add(Login);
        Login.setBounds(130, 230, 240, 23);

        Image_BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kpu/fs/alpha/252505.jpg"))); // NOI18N
        getContentPane().add(Image_BG);
        Image_BG.setBounds(0, 0, 520, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        
        // Main Form to show after the Login Form.
        boolean SecureCheck = true;
        
        String InputUser = UserInput.getText();
        String InputPass = PassInput.getText();
     
        if (InputPass != null || InputUser != null)
        {
            
            if (SecureCheck == true)
            {
                JOptionPane.showMessageDialog(null, "Login Accepted"); 

                this.setVisible(false);
                new JFrame_App().setVisible(true); 
                return;
            }
            
            try
            {
                String Query = "SELECT * FROM LoginInfo";
                ResultSet result = Data_Update.ConncetToDatabase(Query);

                while (result.next())
                {
                    if (result.getString(1).equals(InputUser))
                    {
                        if (result.getString(2).equals(InputPass))
                        {
                            SecureCheck = true;
                        }
                    }
                }
                
                
                if (SecureCheck == true)
                {
                    JOptionPane.showMessageDialog(null, "Login Accepted"); 
                    
                    this.setVisible(false);
                    new JFrame_App().setVisible(true); 
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Wrong Username and Password."); 
                }
            }
            catch(SQLException e)
            {
                JOptionPane.showMessageDialog(null, "SQL ERROR"); 
                JOptionPane.showMessageDialog(null, e); 
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Please enter a Username and Password."); 
        }
    }//GEN-LAST:event_LoginActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_Login().setVisible(true);
                //JFrame_Login.setSize(400, 400);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Image_BG;
    private javax.swing.JButton Login;
    private javax.swing.JLabel Pass;
    private javax.swing.JPasswordField PassInput;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel User;
    private javax.swing.JTextField UserInput;
    // End of variables declaration//GEN-END:variables
}
